### ISSUE TITLE
Missing attribute

### ISSUE THREAD

**Issue by Ispahan** [brownjm/pyGPE#1]
Hello,

I tried to run you code but ran into a few problems.
One of the problems is that inyour ¨timestep.py¨ file,  the potential
class is missing an attribute. I think the problem is: ¨**getattribute**¨ is
not defined. Can you maybe take a look at this problem?

**Comment by brownjm** [comment]
Hi,
Thanks for pointing this out. I developed the code for use with Python 3. Python 2 requires each class to explicitly inherit from 'object' in order to have the method **getattribute**(). I modified the class Potential to inherit from object, but the performance of the animate function is terrible (the time evolution is extremely slow) on my machine using Python 2.7.10. It looks like the problem is with matplotlib's backend qt5 TimerQT object when using Python 2. I don't have this problem using Python 3. I suggest that you try and use Python 3 instead of 2. I hope this helps. Please let me know if there are any other issues. Thanks!

**Comment by Ispahan** [comment]
Hello,

Sorry for my (very) late reply. You are right timestep.py works fine with
python3.
However timestep2d.py does not, I get this error which I do not understand:

Traceback (most recent call last):
  File "timestep2d.py", line 363, in <module>
    'initial': Vortex('wf.dat'),#QHO(n=0,xshift=0),#GaussianWavepacket(1,
0, 0),#QHO(n=0, xshift=0),#File('wf.dat'),  #
  File "timestep2d.py", line 286, in **init**
    self.wf = numpy.load(filename)
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 370, in
load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'wf.dat'

Maybe you recognize it? I tried enabling some of the hashtags, no results.

2015-06-02 18:44 GMT+02:00 Jeffrey M. Brown notifications@github.com:

**Comment by brownjm** [comment]
Hi again,
It says that you are missing the file wf.dat from the current directory. This file is available from this repository. Perhaps you downloaded the repo before I added this around two weeks ago. Please place wf.dat in the same directory as timestep2d.py and try again.

As background for why a file is needed. The Vortex class gives the initial conditions for a BEC vortex embedded in the ground state of a harmonic trap. Since the Vischer's numerical method cannot be modified easily to propagate in complex valued time, in order to find such ground state, then the file spectral.py is used to generate it. If you modify the input parameters of spectral.py to match the inputs of timestep2d.py, then you can generate your own wf.dat and simulate a different vortex and size of BEC.

Hope this helps, let me know if other questions come up.
-Jeff
